hostname: k3s-master
k3os:
  password: supersecure
  token: super-secure-local-cluster-token
  dns_nameservers:
  - 9.9.9.9
  - 1.1.1.1
  ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  k3s_args:
  - server
  - "--disable=traefik"
  - "--node-name=elmaestro"
